### chargeList
GET http://localhost:3000/coinbase/charge/list HTTP/1.1

### chargeAll
GET http://localhost:3000/coinbase/charge/all HTTP/1.1

### chargeAllCompleted
GET http://localhost:3000/coinbase/charge/allCompleted HTTP/1.1

### chargeCreate
POST http://localhost:3000/coinbase/charge/create HTTP/1.1
Content-Type: application/application/json

{
    "name": "Second payment attempt",
    "description": "Second payment attempt by Efebia",
    "local_price": {
        "amount": "5.00",
        "currency": "USD"
    },
    "pricing_type": "fixed_price"
 
}

### chargeDelete
DELETE http://localhost:3000/coinbase/charge/delete/aaa HTTP/1.1